import { notFound } from "next/navigation";
import { Button, StatusBadge, ProductImage } from "@/components/ui";
import { orders } from "@/lib/mock-data";
import { formatCurrency } from "@/lib/format";

export default async function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const order = orders.find((item) => item.id === id) ?? orders[0];
  if (!order) notFound();
  return <div className="account-card"><div className="section-heading"><div><p className="eyebrow">Chi tiết đơn hàng</p><h2>{order.id}</h2><p className="muted">Đặt ngày {order.createdAt}</p></div><StatusBadge status={order.status} /></div><div className="checkout-card" style={{ marginBottom: 18 }}><h3>Trạng thái đơn hàng</h3><div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: 5, textAlign: "center" }}>{["Đã đặt hàng", "Đã xác nhận", "Đang chuẩn bị", "Đang vận chuyển", "Hoàn thành"].map((step, index) => <div key={step}><div style={{ width: 27, height: 27, display: "grid", placeItems: "center", margin: "0 auto 7px", borderRadius: "50%", color: index < 4 ? "white" : "var(--muted)", background: index < 4 ? "var(--accent)" : "var(--line)", fontSize: 11 }}>{index < 4 ? "✓" : index + 1}</div><span className="muted" style={{ fontSize: 9 }}>{step}</span></div>)}</div></div><div className="checkout-card" style={{ marginBottom: 18 }}><h3>Sản phẩm</h3>{order.items.map((item) => <div className="order-body" key={item.product.id}><ProductImage src={item.product.image} alt={item.product.name} className="order-product-img" /><div><strong>{item.product.name}</strong><p>{item.variation} · x{item.quantity}</p></div><strong style={{ marginLeft: "auto" }}>{formatCurrency(item.product.price * item.quantity)}</strong></div>)}</div><div className="checkout-layout" style={{ gridTemplateColumns: "1fr 1fr", gap: 18 }}><div className="checkout-card"><h3>Địa chỉ nhận hàng</h3><p style={{ marginBottom: 3, fontWeight: 700, fontSize: 12 }}>Nguyễn Minh Anh · 090 123 4567</p><p className="muted" style={{ fontSize: 11 }}>42 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh</p></div><div className="summary-card"><h3>Tóm tắt thanh toán</h3><div className="summary-row"><span>Tạm tính</span><strong>{formatCurrency(order.total - 30000)}</strong></div><div className="summary-row"><span>Vận chuyển</span><strong>30.000đ</strong></div><div className="summary-total"><strong>Tổng cộng</strong><strong>{formatCurrency(order.total)}</strong></div><Button variant="outline" style={{ width: "100%" }}>Liên hệ hỗ trợ</Button></div></div></div>;
}
