import Link from "next/link";
import { ButtonLink, SectionHeading } from "@/components/ui";
import { ProductCard } from "@/components/common/ProductCard";
import { ShopCard } from "@/components/common/ShopCard";
import { bestSellerProducts, categories, featuredProducts, flashSaleProducts, newProducts, recommendedProducts, shops } from "@/lib/mock-data";

function ProductSection({ eyebrow, title, description, products, href = "/products", action = "Xem tất cả" }: { eyebrow: string; title: string; description?: string; products: typeof featuredProducts; href?: string; action?: string }) {
  return <section className="page-section"><div className="container"><SectionHeading eyebrow={eyebrow} title={title} description={description} href={href} action={action} /><div className="product-grid">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section>;
}

export default function HomePage() {
  return <>
    <section className="hero"><div className="container"><div className="hero-card"><div className="hero-copy"><p className="eyebrow">Curated marketplace · 09.2026</p><h1>Mua sắm những điều <em>tốt hơn.</em></h1><p>Những sản phẩm được chọn lọc kỹ càng từ các thương hiệu và người bán độc lập đáng tin cậy.</p><div className="hero-actions"><ButtonLink href="/products" size="lg">Khám phá ngay <span>↗</span></ButtonLink><ButtonLink href="/category/dien-tu" variant="outline" size="lg">Xem bộ sưu tập</ButtonLink></div><div className="hero-note"><span>✦</span> Miễn phí vận chuyển cho đơn từ 299K</div></div><div className="hero-floating-card"><span className="hero-floating-icon">✦</span><div><strong>Được chọn kỹ</strong><small>12k+ sản phẩm tốt hơn</small></div></div></div><div className="category-strip">{categories.map((category) => <Link key={category.id} href={`/category/${category.slug}`} className="category-tile"><span className="category-icon">{category.icon}</span><strong>{category.name}</strong><small>{category.count.toLocaleString("vi-VN")} sản phẩm</small></Link>)}</div></div></section>
    <ProductSection eyebrow="Bắt đầu từ đây" title="Những lựa chọn nổi bật" description="Các sản phẩm đang được cộng đồng ecome yêu thích nhất tuần này." products={featuredProducts.slice(0, 4)} />
    <section className="flash-wrap"><div className="container"><div className="flash-header"><SectionHeading eyebrow="Chỉ trong hôm nay" title="Flash sale" description="Giá tốt hơn cho những lựa chọn bạn đã để mắt." href="/products" action="Xem tất cả" /><div className="flash-timer"><span>Kết thúc sau</span><span className="timer-box">06</span><b>:</b><span className="timer-box">42</span><b>:</b><span className="timer-box">18</span></div></div><div className="product-grid">{flashSaleProducts.map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section>
    <ProductSection eyebrow="Bán chạy nhất" title="Những lựa chọn được tin dùng" description="Các sản phẩm có nhiều lượt mua lại và đánh giá tích cực nhất trên ecome." products={bestSellerProducts} action="Xem bảng xếp hạng" />
    <section className="page-section soft-section"><div className="container"><SectionHeading eyebrow="Người bán được yêu thích" title="Những shop có câu chuyện riêng" description="Ghé thăm các cửa hàng độc lập, nơi mỗi sản phẩm đều được chọn bằng sự chăm chút." href="/products" action="Khám phá shop" /><div className="shop-grid">{shops.map((shop) => <ShopCard key={shop.id} shop={shop} />)}</div></div></section>
    <ProductSection eyebrow="Mới lên kệ" title="Có gì mới hôm nay" products={newProducts} />
    <ProductSection eyebrow="Dành riêng cho bạn" title="Một chút cảm hứng cho hôm nay" description="Dựa trên những lựa chọn được yêu thích bởi người dùng có gu tương tự." products={recommendedProducts} action="Xem thêm" />
    <section className="page-section"><div className="container"><div className="promo-grid"><div className="promo-card"><p>Home office edit</p><h3>Góc làm việc, <strong>phiên bản tốt hơn.</strong></h3><ButtonLink href="/category/nha-cua" size="sm" variant="outline">Khám phá</ButtonLink><div className="promo-art" style={{ backgroundImage: "url(https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=500&q=80)" }} /></div><div className="promo-card"><p>New season</p><h3>Chạm vào sự <strong>thoải mái.</strong></h3><ButtonLink href="/category/thoi-trang" size="sm" variant="outline">Xem thời trang</ButtonLink><div className="promo-art" style={{ backgroundImage: "url(https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=500&q=80)" }} /></div><div className="promo-card"><p>Daily ritual</p><h3>Một chút <strong>rạng rỡ</strong> mỗi ngày.</h3><ButtonLink href="/category/lam-dep" size="sm" variant="outline">Xem làm đẹp</ButtonLink><div className="promo-art" style={{ backgroundImage: "url(https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=500&q=80)" }} /></div></div></div></section>
    <div className="container"><div className="benefits"><div className="benefit"><div className="benefit-icon">⌁</div><div><strong>Vận chuyển dễ dàng</strong><span>Miễn phí từ 299K</span></div></div><div className="benefit"><div className="benefit-icon">◈</div><div><strong>Thanh toán an toàn</strong><span>Bảo mật mọi giao dịch</span></div></div><div className="benefit"><div className="benefit-icon">↺</div><div><strong>Đổi trả đơn giản</strong><span>Trong vòng 30 ngày</span></div></div><div className="benefit"><div className="benefit-icon">✦</div><div><strong>Hỗ trợ tận tâm</strong><span>Chúng tôi luôn ở đây</span></div></div></div></div>
  </>;
}
