"use client";

import Link from "next/link";
import { Button, ButtonLink, EmptyState, ProductImage, QuantityInput } from "@/components/ui";
import { useCart } from "@/features/cart/cart-context";
import { formatCurrency } from "@/lib/format";

export default function CartPage() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  if (!items.length) return <div className="container cart-page"><div className="breadcrumbs"><Link href="/">Trang chủ</Link><span>›</span><span>Giỏ hàng</span></div><EmptyState icon="♧" title="Giỏ hàng đang trống" description="Hãy bắt đầu với một vài món đồ bạn yêu thích từ các shop được tuyển chọn trên ecome." action={<ButtonLink href="/products">Khám phá sản phẩm</ButtonLink>} /></div>;
  const groups = items.reduce<Record<string, typeof items>>((result, item) => { const key = item.product.shop.id; result[key] = [...(result[key] ?? []), item]; return result; }, {});
  return <div className="container cart-page"><div className="breadcrumbs"><Link href="/">Trang chủ</Link><span>›</span><span>Giỏ hàng</span></div><div className="section-heading"><div><p className="eyebrow">Túi của bạn</p><h1>Giỏ hàng <span className="muted" style={{ fontSize: 18 }}>({items.length} sản phẩm)</span></h1></div><Link href="/products" className="text-link">Tiếp tục mua sắm →</Link></div><div className="cart-layout"><div>{Object.values(groups).map((group) => <div className="cart-group" key={group[0].product.shop.id}><div className="cart-group-header"><input type="checkbox" defaultChecked aria-label={`Chọn shop ${group[0].product.shop.name}`} /><span>{group[0].product.shop.name}</span><span className="verified">✓</span></div>{group.map((item) => <div className="cart-item" key={`${item.product.id}-${item.variation}`}><input type="checkbox" defaultChecked aria-label={`Chọn ${item.product.name}`} /><ProductImage src={item.product.image} alt={item.product.name} className="cart-thumb" /><div className="cart-item-info"><Link href={`/product/${item.product.slug}`}><strong>{item.product.name}</strong></Link><span>Phân loại: {item.variation ?? "Mặc định"}</span></div><QuantityInput value={item.quantity} onChange={(value) => updateQuantity(item.product.id, value)} /><strong className="cart-item-price">{formatCurrency(item.product.price * item.quantity)}</strong><button className="remove-link" onClick={() => removeItem(item.product.id)}>Xóa</button></div>)}</div>)}</div><aside className="summary-card"><h3>Tóm tắt đơn hàng</h3><div className="summary-row"><span>Tạm tính</span><strong>{formatCurrency(subtotal)}</strong></div><div className="summary-row"><span>Phí vận chuyển</span><strong>{subtotal >= 299000 ? "Miễn phí" : formatCurrency(30000)}</strong></div><div className="voucher-field"><input placeholder="Mã giảm giá" aria-label="Mã giảm giá" /><Button size="sm" variant="outline">Áp dụng</Button></div><div className="summary-total"><strong>Tổng cộng</strong><strong>{formatCurrency(subtotal >= 299000 ? subtotal : subtotal + 30000)}</strong></div><ButtonLink href="/checkout" size="lg">Tiến hành thanh toán <span>→</span></ButtonLink><p className="muted" style={{ margin: "13px 0 0", fontSize: 10, textAlign: "center" }}>Thanh toán an toàn · Đổi trả dễ dàng</p></aside></div></div>;
}
