import Link from "next/link";
import { ButtonLink, StatusBadge } from "@/components/ui";
import { ProductImage } from "@/components/ui";
import { orders, products } from "@/lib/mock-data";
import { formatCurrency } from "@/lib/format";

export default function AccountPage() {
  return <div className="account-card"><div className="profile-head"><div className="profile-photo">MA</div><div><h2>Chào Minh Anh,</h2><p>Đây là những gì đang diễn ra với tài khoản của bạn.</p></div><ButtonLink href="/account/profile" variant="outline" size="sm" style={{ marginLeft: "auto" }}>Chỉnh sửa hồ sơ</ButtonLink></div><div className="stats-grid" style={{ marginTop: 22, marginBottom: 22 }}><div className="stat-card"><div className="stat-top">Đang giao<span className="stat-icon">⌁</span></div><div className="stat-value">1</div><div className="stat-change">Đơn hàng đang trên đường</div></div><div className="stat-card"><div className="stat-top">Đã hoàn thành<span className="stat-icon">✓</span></div><div className="stat-value">12</div><div className="stat-change">+3 trong tháng này</div></div><div className="stat-card"><div className="stat-top">Điểm ecome<span className="stat-icon">✦</span></div><div className="stat-value">820</div><div className="stat-change">Còn 180 điểm lên hạng</div></div></div><div className="section-heading" style={{ marginTop: 30, marginBottom: 15 }}><h2>Đơn hàng gần đây</h2><Link href="/account/orders" className="text-link">Xem tất cả →</Link></div>{orders.slice(0, 2).map((order) => <div className="order-card" key={order.id}><div className="order-head"><span className="order-shop"><span className="mini-avatar">N</span>{order.shop.name}</span><StatusBadge status={order.status} /></div><div className="order-body"><ProductImage src={order.items[0].product.image} alt={order.items[0].product.name} className="order-product-img" /><div><strong>{order.items[0].product.name}</strong><p>{order.items[0].variation} · x{order.items[0].quantity}</p><p>{order.items.length > 1 ? `+${order.items.length - 1} sản phẩm khác` : ""}</p></div></div><div className="order-footer"><span>{order.id} · {order.createdAt}</span><div className="order-total"><span>Tổng cộng</span><strong>{formatCurrency(order.total)}</strong></div></div></div>)}<div className="section-heading" style={{ marginTop: 30, marginBottom: 15 }}><h2>Gợi ý cho bạn</h2><Link href="/products" className="text-link">Xem thêm →</Link></div><div className="product-grid">{products.slice(0, 2).map((product) => <div key={product.id}><Link href={`/product/${product.slug}`}><ProductImage src={product.image} alt={product.name} /></Link><p style={{ margin: "8px 0 0", fontWeight: 700, fontSize: 12 }}>{product.name}</p></div>)}</div></div>;
}
